#import "../plantilla/bloques.typ": pendiente, nota, tabla, figura-pendiente

= Marco teórico

== Digitalización y conservación de filmes

El filme cinematográfico es una tira flexible formada por un material de base plástico y transparente, y una emulsión fotosensible de gelatina adherida a él. La imagen y el sonido óptico viven en la emulsión, mientras que la base sostiene esa información y es lo que un sistema de transporte efectivamente manipula. Los calibres que le interesan a este proyecto, 16 mm y 35 mm, quedan definidos por el ancho de la tira y por las dimensiones y el paso de sus perforaciones.

A lo largo del siglo se usaron tres materiales de base, y la diferencia entre ellos determina en qué estado llega hoy el material al laboratorio. El *nitrato de celulosa*, empleado hasta comienzos de la década de 1950, es químicamente inestable y altamente inflamable. Los *acetatos de celulosa*, primero diacetato y luego triacetato, se comercializaron como "safety film" por su menor riesgo de combustión, que es una propiedad distinta de la estabilidad química: un acetato nuevo guardado a 18 °C y 50 % de humedad relativa tarda alrededor de 50 años en manifestar los primeros signos de síndrome del vinagre, y bastan 8 °C menos para postergarlos otros 150 @nfpf-guide. El *poliéster*, introducido comercialmente hacia mediados de la década de 1950, es el primero que resulta estable en lo químico y en lo dimensional a largo plazo. El acervo del CDA es mayoritariamente acetato, que es la familia intermedia.

La forma característica en que se degrada el acetato es el *síndrome del vinagre*. La base de acetato se hidroliza, libera ácido acético, y es el olor de ese ácido lo que da nombre al fenómeno. #nota[Lo que vuelve grave al síndrome del vinagre es que la reacción es autocatalítica: el ácido liberado acelera la hidrólisis que lo produce. Una vez iniciada, la degradación no se detiene ni se revierte, solo se ralentiza bajando la temperatura y la humedad de guarda @nfpf-guide.] Más allá del olor, los síntomas observables son el encogimiento de la base, la pérdida de flexibilidad y el enrulado, la emulsión cuarteada y un polvo blanco sobre los bordes @nfpf-guide. El primero es el que gobierna todo lo que sigue: el filme no llega al sistema con las dimensiones con las que fue fabricado.

#figura-pendiente(
  [Fotografía de material del propio acervo en distintos estados de conservación, sobre mesa de luz y con una escala en el encuadre. Debería mostrar, en lo posible en una sola toma comparativa: un rollo en buen estado, uno con encogimiento y deformación ondulada visibles, y una tira con perforaciones rasgadas o faltantes. Si el CDA usa A-D Strips, incluir una junto al rollo con su lectura visible.],
  caption: [Estados de conservación del acetato en el acervo del CDA.],
) <fig-deterioro>

=== Perforaciones y paso

Las perforaciones cumplen dos funciones a la vez: son el apoyo mecánico del transporte, sea por rueda dentada, garra o capstan, y son la referencia geométrica que permitía registrar cada fotograma en su posición. Su paso, la distancia entre dos perforaciones consecutivas, está normalizado por la Society of Motion Picture and Television Engineers (SMPTE) en dos variantes por calibre, y la razón de que sean dos ya es una consecuencia del encogimiento: el positivo se perfora con un paso 0,2 % más largo que el negativo del que se lo copia, para compensar lo que ese negativo se contrae durante el revelado y el almacenamiento previos @smpte-st102. Antes de cualquier deterioro, la geometría nominal del filme está calculada alrededor de una contracción esperada.

#figure(
  tabla(
    columnas: (auto, auto, auto, auto),
    cabecera: ("Calibre", "Perforación y uso", "Paso", "Norma"),
    [35 mm], [CS-1870, copias], [0,1870 ± 0,0004 in (4,750 ± 0,010 mm)], [SMPTE 102 @smpte-st102],
    [35 mm], [BH y KS, negativos e intermedios], [0,1866 in (4,740 mm)], [SMPTE 93 @smpte-93, SMPTE 139 @smpte-139],
    [16 mm], [1R-3000 y 2R-3000, copias], [0,3000 in (7,620 mm)], [SMPTE 109 @smpte-109],
    [16 mm], [1R-2994 y 2R-2994, negativos], [0,2994 in (7,605 mm)], [SMPTE 109 @smpte-109],
  ),
  kind: table,
  caption: [Pasos de perforación normalizados por calibre y variante. En ambos calibres la diferencia entre las dos variantes es de alrededor del 0,2 %, que es la contracción que la norma prevé para el negativo. El paso largo de 16 mm queda además corroborado por @smpte-rp74, que lo declara como el paso del filme sin encogimiento sobre el que calcula la geometría del diente.],
) <tbl-pasos>

#nota[Los códigos siguen el sistema de nomenclatura que SMPTE aplica a todas sus normas de dimensiones de filme: el título indica el ancho, luego un código de forma de perforación (BH, KS, DH o CS) o bien la cantidad de hileras (1R, 2R), según cuál sea el factor significativo en ese calibre, y por último el paso escrito sin la coma decimal @smpte-st102. Por eso el 35 mm se identifica por forma y el 16 mm por hileras.]

El 16 mm admite dos configuraciones de perforado, ambas en esa misma norma @smpte-109: en 2R hay una hilera a cada lado de la tira, y en 1R queda una sola, porque el borde liberado es donde corre la pista de sonido óptico. De ahí sale R12, que obliga a capturar ambos bordes para que el flujo de extracción de sonido del CDA siga teniendo con qué trabajar. La práctica del campo le da nombre a esa exigencia: se la llama *sobrebarrido* (_overscan_), y la FIAF la recomienda para que se capturen el fotograma completo y hasta las perforaciones, señalando que un barrido de ancho y alto completos sobre una copia sonora captura además una imagen utilizable de la banda de sonido, y que existe tecnología que reconstruye el audio a partir de los fragmentos de pista que acompañan a cada fotograma sobrebarrido @fiaf-choosing-scanner. #nota[La misma guía advierte la contrapartida óptica: si la perforación entra en el encuadre, la luz que la atraviesa llega al sensor sin ser modulada por ninguna densidad del filme y puede producir velo. Es un dato de diseño para la iluminación del capítulo 6, no un motivo para recortar el encuadre.] Y de ahí sale una restricción más fina para el capítulo 9: un algoritmo que ubique el fotograma por las columnas donde aparecen las perforaciones no puede asumir cuántas hileras va a encontrar.

#figura-pendiente(
  [Fotografía a contraluz de tiras del acervo apoyadas sobre la misma mesa de luz y a la misma escala, con una regla en el encuadre: una de 35 mm y una de 16 mm, y dentro del 16 mm una tira de doble perforación junto a una de perforación simple. Tiene que dejarse ver el borde liberado de la tira 1R, que es donde corre la pista de sonido óptico.],
  caption: [Geometría comparada de 16 mm y 35 mm sobre material del acervo. El área marginal que se ve a los costados del fotograma es la que el requerimiento R12 obliga a mantener dentro del encuadre.],
) <fig-geometria>

Todas esas cifras describen filme nuevo, y las normas lo dicen explícitamente: rigen en el momento del corte y perforado, sobre filme acondicionado a 23 °C y 50 % de humedad relativa @smpte-st102. En un rollo que pasó décadas en un depósito el paso deja de ser constante y de ser conocido.

A partir de cierto encogimiento el arrastre por perforaciones deja de funcionar, y tres fuentes independientes coinciden en dónde está ese límite. La norma de diseño de ruedas dentadas de 16 mm de SMPTE le reserva a cada diente una holgura que absorbe alrededor de 0,6 % de encogimiento, con 0,8 % como techo @smpte-rp74. #nota[RP 74 está clasificada por SMPTE como documento Stable, vigente pero no representativo de la tecnología actual. Se la cita justamente por eso: el material tampoco es actual.] La guía de preservación de la National Film Preservation Foundation fija el mismo 0,8 % como el punto donde una película de 16 mm puede dañarse al proyectarse, y el 2 % como aquel donde hasta un laboratorio especializado tiene dificultades para copiarla @nfpf-guide. Y la guía de la FIAF para elegir un escáner señala que el registro por pines, que inmoviliza el fotograma calzando pines en sus perforaciones y por eso solo existe en equipos que detienen el filme, vuelve a esos equipos muy poco tolerantes a originales encogidos, al punto de que para material de archivo hay que deshabilitarlo y pasar a estabilización por software @fiaf-choosing-scanner. Es decir que la propia práctica profesional, ante material de archivo, abandona la perforación como referencia y se pasa a la imagen.

El encogimiento castiga además más a los calibres chicos, por el fotograma más pequeño y la mayor precisión que le exigen al equipo, y el acervo del CDA es mayoritariamente 16 mm.

El material que este sistema tiene que digitalizar es, por definición, el que ya está fuera de ese rango: si el archivo pudiera proyectarlo o copiarlo por medios convencionales de tracción en las perforaciones, no haría falta construir un sistema de detección.

=== Las funciones de un digitalizador

Un digitalizador de filme resuelve tres problemas de naturaleza distinta, y por eso el sistema se divide en tres subsistemas antes que en uno solo. El *transporte* mueve el filme sin dañarlo y sin asumir que su paso es fijo, y es un problema mecánico y de potencia. La *detección* establece, fotograma a fotograma, cuánto se desvía el encuadre del centro, y es un problema de medición sobre material cuya geometría no es confiable. La *captura* registra la imagen una vez que la detección la habilita, y es un problema óptico y de control remoto. Las secciones 2.2, 2.3 y 2.4 desarrollan cada una en ese orden, y los capítulos 8, 9 y 10 las implementan en el mismo.

La forma de coordinar las tres admite dos esquemas. En el *continuo*, el filme nunca se detiene y la captura se sincroniza con el movimiento, ya sea mediante un sensor lineal que compone la imagen a medida que la tira pasa, ya sea congelando el fotograma en movimiento con iluminación estroboscópica o con un obturador suficientemente rápido. En el *intermitente*, el transporte avanza, se detiene, la detección confirma el centrado y recién entonces se dispara. El continuo alcanza cadencias mayores y le exige al sistema un sincronismo fino y sostenido entre transporte y obturador. El intermitente tolera que el paso entre fotogramas varíe, porque cada avance se corrige contra lo que la detección midió en ese fotograma y no contra una distancia nominal.

Este trabajo adopta el esquema intermitente. La industria de preservación usa los dos, y de hecho dos de los equipos que compara 2.5 son continuos, pero el intermitente tiene una familia establecida: la guía de la FIAF ubica ahí a los escáneres orientados a producción de alta calidad, preservación y restauración, como el ARRISCAN y el Northlight, donde el filme avanza de a un fotograma y se sostiene quieto en la ventanilla mientras se lo captura @fiaf-choosing-scanner. En esos equipos, según la misma guía, lo habitual es aprovechar la parada para calzar pines en las perforaciones y fijar el cuadro, que es justamente la técnica que desaconseja sobre material encogido. Este trabajo conserva el esquema y reemplaza esa pieza: la parada deja de servir para sujetar el fotograma y pasa a servir para mirarlo.

== Transporte

De la sección anterior resultó descartado el arrastre por perforaciones, por lo que la primera pregunta es cómo mover material fílmico al que no se le puede tomar de sus agujeros. La alternativa es el arrastre por fricción: un rodillo capstan contacta con el filme (evitando la zona de emulsión) y lo hace avanzar por adherencia sobre la superficie de la base. El paso deja de importar, porque el mecanismo ya no busca calzar en ninguna geometría, y con él desaparece la carga sobre el borde de la perforación contra la que advierte la propia norma de diseño de ruedas dentadas @smpte-rp74.

El avance como tal es una de las tres funciones que el transporte cumple a la vez, y cada una tiene su elemento. El *capstan* impone el avance real. El *plato alimentador*, o de suministro, entrega filme desde el rollo de origen sin tironear. El *plato receptor* lo recoge en el rollo de destino sin dejarlo flojo. #nota[La literatura del área está casi toda en inglés, donde los tres son *capstan*, *feed reel* y *takeup reel*. Capstan se usa sin traducir.] En los tres casos, el vínculo entre lo que hace el motor y lo que le pasa al filme es un factor de conversión que no es constante. En los platos, la tensión es el par dividido por el radio, y el radio cambia a lo largo de la digitalización: a par constante, el filme se tensa cada vez más a medida que el rollo de origen se achica. En el capstan, cada vuelta entrega una longitud fija de filme, pero la longitud que hace falta para avanzar un fotograma es el paso del material, que encogió, de modo que el giro por fotograma es una propiedad variable en cada rollo. La distinción entre el elemento que hace avanzar el filme contra los elementos de suministro es estándar en la industria, y se traduce en tres puntos de actuación independientes.

Entre un plato y el otro el filme va hilado a lo largo de un camino fijo, apoyado sobre rodillos guía que cumplen tres funciones a la vez: definen la geometría del recorrido, mantienen la tira plana y alineada lateralmente, y desacoplan tramos, de modo que una perturbación de tensión en uno no se propague al siguiente. Como el filme se guarda enrollado y viaja apoyado sobre superficies cilíndricas, todo elemento del camino es un cuerpo sujeto a rotación y toda actuación se ejerce como un par sobre un eje: el avance lineal de la tira es el resultado de movimientos rotacionales, y en el transporte no hay ningún actuador que se desplace.

De ahí sale lo que se le pide a cada actuador: un avance discreto y repetible del orden del paso de un fotograma, la capacidad de sostener la posición mientras la cámara expone, y un par de torque acotado, porque sobre una base fragilizada la fuerza disponible es un riesgo antes que una virtud.

=== Del actuador al driver

Los actuadores rotativos que pueden resolver eso se distinguen, más que por su construcción, por cuánto saben de la posición real de su propio eje. Un motor de corriente continua gira mientras se lo alimente y no sabe nada, así que posicionar con él exige agregarle un sensor y un lazo de control externos. Un servomotor trae ese lazo de fábrica, ya que integra el motor, un encoder y un controlador que compara la posición pedida con la medida y corrige la diferencia. El motor paso a paso ofrece una tercera vía: su rotor avanza un incremento angular fijo por cada pulso que recibe, de modo que contar pulsos alcanza para saber cuánto se movió, sin medir nada.

Esa tercera vía es la habitual para avances discretos y repetitivos como el de un fotograma. La electrónica es más simple y barata que la de un servo, el comportamiento es predecible, y su uso masivo en impresoras 3D, máquinas de control numérico (CNC) y automatización de laboratorio dejó una oferta madura de componentes de bajo costo. 


Entre la lógica y el motor hace falta una etapa intermedia, porque un microcontrolador no puede alimentar las bobinas: la corriente, la tensión y la energía almacenada en la inductancia están fuera de lo que un pin puede manejar. De eso se ocupa el *driver*, un circuito integrado que combina la etapa de potencia con la lógica de secuencia y, en los modelos actuales, con una regulación por conmutación que mantiene en cada bobina la corriente configurada en lugar de la que impondría la tensión de alimentación. El TMC2209, que es el driver que adopta el capítulo 6, es un caso concreto de esa categoría @tmc2209-datasheet. El controlador le habla por dos vías: líneas discretas de paso, dirección y habilitación, que son el mínimo común de la categoría, y en los modelos configurables un enlace serie que da acceso a sus registros internos. #nota[Como el driver es un integrado de montaje superficial de pines muy finos, se lo monta sobre una placa portadora que expone sus señales en un formato común. Esa convención es la que permite que el capítulo 6 discuta qué driver conviene sin que la decisión arrastre al resto del diseño.]

Casi todos ofrecen además *micropaso*, que subdivide electrónicamente cada paso mecánico en fracciones y suaviza el movimiento. Es la unidad en la que el capítulo 8 razona el avance, porque un paso completo puede contener hasta 256 micropasos.

=== Nadie mide el eje en un motor paso a paso

El driver sabe cuántos pulsos emitió y el firmware sabe cuántos pidió, pero nadie mide el eje: no hay sensor que confirme que el rotor giró lo que se le ordenó. Si el par requerido supera momentáneamente al disponible, por fricción, inercia o un obstáculo, el motor pierde pasos o se detiene, y la cuenta sigue avanzando como si nada hubiera ocurrido. Que esto ocurre lo reconoce el propio fabricante: el TMC2209 incorpora una función que estima la carga sobre el eje a partir de la respuesta eléctrica del motor y señala el atasco por un pin dedicado @tmc2209-datasheet. Pero eso informa un evento y no una posición, y no dice cuántos pasos se perdieron antes de avisar.

El arrastre por fricción aporta la segunda mitad del problema. Al no engranar en ninguna geometría, un capstan puede deslizar sobre el filme, de modo que incluso con el motor girando exactamente lo comandado el avance real de la tira puede diferir del calculado. Lo que se ganó al abandonar la perforación como apoyo mecánico se paga de esta forma.

Entonces, la cuenta de pasos es una estimación del avance y nunca una medición. Además, como se discutió en 2.1, todo material degradado tiene un paso con deriva, por lo que no hay forma de convertir movimiento constante en la posición del fotograma. Por lo tanto, como el mecanismo no puede saber dónde quedó el fotograma, hay que mirarlo.


== Detección del centrado

El transporte deja el filme detenido en una posición que nadie verificó. Cerrar ese vacío es tarea de un subsistema cuya función no es mover el filme sino decidir, a partir de lo que efectivamente se ve, si el fotograma está centrado y cuánto le falta para estarlo. Extraer de una imagen una magnitud que sirva para tomar esa decisión, en lugar de que un operador la juzgue a ojo, es el objeto de la *visión artificial*. Aplicada al centrado, la pregunta deja de ser si el fotograma está bien encuadrado y pasa a ser cuántos píxeles está desviado, en qué dirección y con qué certeza: una magnitud que se registra, se compara entre corridas y, sobre todo, se realimenta al transporte para corregir el avance siguiente.

=== Qué tiene que entregar la detección

Antes de comparar métodos conviene fijar contra qué se los compara, porque el problema impone cuatro condiciones y no todas son técnicas.

La salida tiene que ser una *magnitud y no un evento*: un desplazamiento en píxeles con su dirección, acompañado de una confianza que permita distinguir un centrado válido de uno que no convergió, que es la condición de detención especificada en 1.3. Tiene que ser *auditable*, en el sentido de que ante un resultado dudoso se pueda reconstruir por qué el método decidió lo que decidió. No puede *depender de la geometría de fábrica de la perforación*, porque 2.1 ya estableció que el material no la conserva. Y tiene que ser *reproducible por la institución*, con las herramientas y el conocimiento que el laboratorio pueda sostener, que es el argumento de soberanía técnica de 1.2 aplicado al software.

=== Métodos sobre la imagen

Los *métodos geométricos* explotan que, a contraluz, las perforaciones son rectángulos brillantes sobre una base oscura. Un umbralado seguido de la búsqueda de componentes conexas entrega centroides y, de paso, área y relación de aspecto, que sirven para descartar las perforaciones rotas. Los perfiles de proyección atacan lo mismo sumando la imagen por filas y columnas: como las perforaciones son periódicas a lo largo de la tira, aparecen como un tren regular de picos cuya fase es el desplazamiento. Son los métodos más baratos y los más fáciles de auditar, porque cada paso intermedio es una imagen que se puede mirar.

La *correlación cruzada* responde la pregunta de otra forma: compara una plantilla de referencia, por ejemplo el borde del fotograma, contra las regiones candidatas de la imagen actual y retiene la posición donde mejor coinciden. La variante habitual es la *correlación cruzada normalizada* (NCC), que expresa esa coincidencia como un coeficiente entre $-1$ y $1$ e introduce una normalización que la vuelve insensible a cambios lineales de brillo y contraste, de modo que dos fotogramas expuestos de forma distinta siguen siendo comparables @lewis1995. La posición del máximo es el desplazamiento y la nitidez del pico es la confianza, así que el método entrega las dos magnitudes que pide 2.3.1 sin trabajo adicional. #nota[La NCC entre una plantilla $t$ y una región de imagen $f$ se calcula restando a cada una su valor medio antes de correlacionar y dividiendo por el producto de sus desviaciones estándar.] Una variante ataca el mismo problema desde el dominio de la frecuencia: dos imágenes relacionadas por un desplazamiento difieren solo en la fase de su transformada de Fourier, y al normalizar el espectro cruzado y antitransformarlo aparece un pico agudo cuya posición es ese desplazamiento.

El *aprendizaje automático* también resuelve el problema, y sobre perforaciones muy deterioradas probablemente lo resuelva mejor que una plantilla fija. Se descarta por las dos últimas condiciones de 2.3.1, no por la primera. Entrenar un modelo exige un conjunto etiquetado de material del propio acervo, con su deterioro característico, que es un proyecto en sí mismo; y el resultado es un binario opaco que el laboratorio tendría que poder reentrenar para mantener, lo que reintroduce por la vía del software la misma dependencia de proveedor que el capítulo 1 identifica como el problema a resolver.

=== La alternativa: detectar la perforación

La otra vía no mira la imagen sino que sensa el paso de la perforación por un punto fijo del recorrido, y sincroniza la captura con ese pulso. La versión óptica usa un fotodiodo o fototransistor; la mecánica, un microrruptor de palanca que cierra contacto cuando el palpador cae en el agujero. Las dos son precisas mientras la perforación conserve su geometría, y las dos fallan sobre material rasgado, deformado por encogimiento o directamente sin perforaciones (@fig-deterioro). La mecánica agrega un problema propio: apoya un palpador sobre la tira, de modo que la referencia se obtiene tocando el mismo material que se pretende preservar.

Ninguna de las dos entrega una magnitud, sino un evento, así que incumplen la primera condición antes incluso de llegar a la del deterioro. La medición sobre la imagen es la que las cumple todas, y es la que cierra el vacío que dejó el transporte en lazo abierto: donde el motor paso a paso no sabe cuántos pasos se tradujeron en movimiento, la imagen mide cuadro a cuadro dónde terminó estando el fotograma. El capítulo 9 desarrolla esa medición y decide entre los métodos de 2.3.2, con la restricción que ya impuso 2.1: no puede asumir cuántas hileras de perforaciones va a encontrar.

#pendiente[Leer bien las referencias]

== Captura

Confirmado el centrado, queda una sola tarea: registrar la imagen. Los dispositivos que la cumplen se clasifican, antes que nada, por la arquitectura de su sensor. Un sensor de barrido lineal (*line-scan*) construye la imagen una línea por vez, sincronizado con el movimiento del filme. Un sensor de área (*area-scan*) expone el fotograma completo de una sola vez, como una fotografía. Esa distinción atraviesa a las dos familias de equipos: los escáneres dedicados, que integran óptica, sensor, iluminación y transporte en un mismo cuerpo, y los sistemas basados en una cámara fotográfica que registra cada fotograma detenido a través de un objetivo macro. Los segundos son de área por construcción, porque una cámara fotográfica expone todo su sensor en cada disparo.

Los escáneres de gama alta optan por sensores lineales, que no registran el fotograma de una vez sino que lo construyen como una sucesión de exposiciones línea por línea mientras el filme se desplaza sobre una ranura estrecha, de forma análoga a una copiadora continua. Es el principio del Spirit y del Goldeneye 4, y el DFT Scanity lo refina con varios arreglos lineales, de modo que cada franja de la imagen la capta un sensor distinto por turno y el resultado se compone a partir de la salida de todos @fiaf-choosing-scanner. Esa arquitectura impone una condición: la velocidad de lectura del sensor tiene que estar sincronizada de forma sostenida con la de avance del material.

Un sensor de área no necesita esa sincronización. Alcanza con un disparo por fotograma, sin ninguna relación entre el tiempo de exposición y la velocidad de avance, y por eso encaja de forma natural con el esquema intermitente de 2.1: el filme avanza, se detiene, la detección confirma el centrado, se dispara. La arquitectura de captura no es una elección independiente, sino la consecuencia de haber elegido un transporte de paradas discretas.


=== Lo que hace utilizable a una cámara fotográfica

Capturar no alcanza. Para que una cámara sirva dentro de un sistema automatizado tiene que exponer una interfaz de *control remoto*, es decir la posibilidad de accionar el obturador, ajustar la exposición y transferir la imagen por software, sin que nadie toque el cuerpo. Esa interfaz es la que permite que el subsistema de detección dispare la captura en el instante en que confirma el centrado, y es lo que cierra el ciclo por fotograma.

Canon publica dos interfaces para eso. EDSDK (*EOS Digital Software Development Kit*) es una biblioteca en C que habla con la cámara por USB, y CCAPI (*Camera Control API*) expone las mismas funciones como peticiones HTTP sobre red, lo que la vuelve independiente del lenguaje y del sistema operativo del lado del control @canon-sdk. #nota[Ninguna de las dos se descarga sin más: el acceso a los paquetes pasa por un formulario de solicitud y por la aprobación del programa de desarrolladores de Canon @canon-sdk-solicitud. Es una dependencia de proveedor sobre el flujo de trabajo, no sobre el equipo, y conviene tenerla presente al leer el argumento de soberanía técnica de 1.2.]

La Canon EOS R50 del laboratorio es un caso concreto de cámara con esa capacidad: sin espejo, sensor CMOS APS-C de 24,2 megapíxeles, hasta 15 cuadros por segundo con obturador electrónico @canon-r50. Admite ambas interfaces, verificado sobre el equipo del CDA, y el capítulo 10 desarrolla cuál de las dos adopta el sistema y por qué.

La contrapartida de esta arquitectura es previsible y conviene declararla acá: la relación señal a ruido y la resolución de una cámara de consumo quedan por debajo de las de un TDI profesional. Sin embargo, sigue siendo la arquitectura que corresponde a un transporte de paradas discretas con decisión por fotograma, bajo la restricción de reutilizar el equipamiento que el laboratorio ya tiene.

Frente a material deteriorado, además, la diferencia entre las dos arquitecturas no es solo de calidad sino de modo de falla, y ahí el sensor de área tiene ventaja. Si el avance del filme se altera, en un sensor lineal la imagen se construye línea por línea sobre un movimiento que dejó de ser uniforme, y el resultado es una deformación u ondulación del fotograma; en un sensor de área el cuadro entero se desplaza como bloque, que es un error corregible en el posproceso @fiaf-choosing-scanner. Sobre perforaciones rasgadas y encogimiento heterogéneo, ese comportamiento importa más que la resolución nominal.
== Estado del arte

En cuanto a los proyectos existentes, la propia FIAF mantiene un catálogo de los escáneres que usan los archivos del mundo, con alrededor de cuarenta modelos separados en tres categorías: equipos comerciales, prototipos comerciales y prototipos de archivo; comparados por ejes que incluyen la capacidad de transportar sin dentado, el sobrebarrido, los calibres admitidos y la resolución @fiaf-scanners. Esa clasificación es la que ordena esta sección, y su tercera categoría es la que explica por qué un desarrollo como este tiene lugar dentro del campo y no al margen.

Conviene advertir de entrada por qué lo que sigue no es una tabla de especificaciones enfrentadas. La guía técnica de la FIAF señala que los fabricantes de escáneres no publican, por lo general, información objetiva sobre el desempeño de sus equipos, y que tampoco existe material de prueba estandarizado con el cual medirlos, de modo que evaluar si un escáner sirve para un archivo determinado termina siendo cuestión de armar un juego de piezas de prueba propio y ensayarlo @fiaf-choosing-scanner. La comparación detallada que uno esperaría encontrar no está disponible para nadie, y esa opacidad es en sí misma un dato sobre el mercado al que este proyecto responde.

=== Los equipos comerciales

Del lado comercial, las decisiones de arquitectura que discutieron 2.2 y 2.4 aparecen repartidas. Los equipos orientados a producción de alta calidad, preservación y restauración, como el ARRISCAN y el Northlight, son intermitentes: avanzan un fotograma, lo sostienen quieto en la ventanilla y lo capturan. Otros, como el Lasergraphics ScanStation y el MWA Vario, corren el filme de forma continua y congelan la imagen con un pulso estroboscópico corto. Y una tercera familia, la del Spirit, el Goldeneye 4 y el DFT Scanity, construye el fotograma con sensores lineales @fiaf-choosing-scanner.

Lo relevante para este trabajo es que ninguna de esas familias resuelve el centrado de un modo que sirva sobre material de archivo sin renunciar antes a su propio método. Los intermitentes, que son los que comparten esquema con este proyecto, sostienen el cuadro con pines calzados en las perforaciones, y ya se vio en 2.1 que la propia guía indica deshabilitarlos ante originales encogidos y pasar a estabilización por software. Los lineales agregan un problema distinto: si el avance se perturba, la imagen se construye sobre un movimiento que dejó de ser uniforme y el fotograma sale deformado, mientras que un sensor de área desplaza el cuadro entero como bloque, que es un error corregible después @fiaf-choosing-scanner.

El obstáculo, sin embargo, no es técnico sino económico e institucional. La misma opacidad que impide comparar desempeños alcanza a los precios. Ningún fabricante de esta categoría publica una lista, así que el costo solo se conoce pidiendo cotización. Las que relevó el CDA durante la elicitación rondaron los USD 50.000 y el laboratorio señala que ese es el orden de magnitud habitual del rubro. La cifra excede cualquier presupuesto que la institución pueda destinar al problema. A eso se suma que un equipo cerrado trae consigo una dependencia: repararlo exige que una oficina de soporte exista y siga operando en la región.

=== Los prototipos de archivo

La tercera categoría del catálogo reúne a los desarrollos hechos por los propios archivos, y ahí el antecedente más cercano a este trabajo está documentado con detalle. El escáner del LAPA, el Laboratorio de Preservación Audiovisual de la Universidad de la República de Uruguay, reconvirtió un telecine Rank-Cintel en desuso en un escáner fotograma a fotograma para 8, 16 y 35 mm, con software libre y sin licencias propietarias @lapa-scanner. Su reparabilidad no es incidental sino de diseño: los componentes se eligen para poder sustituirse según el presupuesto y lo que se consiga en el mercado local, y el propio equipo documenta haber reemplazado cámara, controlador e iluminación a lo largo de los años. Es el trabajo más próximo a este por calibre, por escala institucional y por el planteo de soberanía tecnológica que 1.2 desarrolla.

El mismo trabajo describe a su antecedente, Kinograph, de Matthew Epler: un arrastre de baja velocidad integrado con una ventanilla de luz difusa y una cámara con objetivo macro, disparada por un mecanismo de sincronización cada vez que un fotograma queda posicionado en la ventanilla @lapa-scanner. Los dos comparten la premisa de que la memoria cultural no debería depender de cuánto dinero tenga quien la preserva, y los dos resuelven la posición del cuadro por la vía del mecanismo.

Ahí está el límite de esta familia. El LAPA aprovecha el transporte del propio telecine, que mueve el filme sin usar las perforaciones, y sincroniza el disparo con la señal de arrastre del mecanismo, primero con una Raspberry Pi y después con una placa Arduino Due @lapa-scanner. La posición del cuadro queda atada a la mecánica del transporte y no medida sobre la imagen, de modo que el sistema no entrega una magnitud de centrado por fotograma. Sus autoras señalan además que el proceso difícilmente pueda automatizarse por completo y que el material deteriorado exige ajustes manuales y a medida.

=== El espacio vacante

Enunciado con precisión, el espacio que ocupa este proyecto es más angosto que la oposición entre lo comercial y lo abierto. No es la ausencia de un escáner abierto para 16 y 35 mm, que el LAPA ya demostró posible. Es la ausencia de uno que ubique el fotograma midiendo sobre la propia imagen, en lugar de deducirlo del mecanismo de transporte o del estado de la perforación, que entregue una magnitud de centrado verificable por cuadro, y que documente el proceso de requerimientos y verificación que desarrolla el capítulo 3.
